### ISSUE TITLE
[AOEII:DE] Downloads not working at all

### ISSUE THREAD

**Issue by anzz1** [SiegeEngineers/aoe2map#57]
**How to reproduce**

1. Go to https://aoe2map.net/map/835476/manglegrove
2. Select "Download ZIP for DE mod" from the "Download map" dropdrown menu
3. Nothing happens

Tested on Firefox 111.0.2 and 112.0 (Windows x64)

**Comment by HSZemi** [comment]
Thank you for the report! It looks like I made a small mistake there, which is why the zip downloads on the individual map pages did not work. That should be resolved now.

Whoever uploads a map script has the option to indicate a mod that the map script is a part of. You can see an example of this [here](https://aoe2map.net/map/231878/bagasm). But if they don't, there's no link, sorry.
